spring:
  profiles:
    active: db, core, wx
  messages:
    encoding: UTF-8

server:
  port: 8080

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.jenny.shopping.wx:  DEBUG
    com.jenny.shopping:  ERROR

swagger:
  production: false
